repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/psf/black
    rev: 23.11.0  # Use the sha / tag you want to point at
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
